export const options = [
    'Tinfoil Chicken', 
    'Chicken Fajitas', 
    'Beef Tacos', 
    'Stir Fry', 
    'Daal Chawal', 
    'Chicken Karahi',
    'Jambalaya',
    'Burgers',
    'Keema Curry with Rice and Veggies',
    'Salmon with Rice and Veggies',
    'Sushi',
    'Salmon with Pasta and Veggies',
    'Spaghetti',
    'Chili',
    'Shredded Beef With Potato',
    'Baked Potato',
    'Roast Chicken',
    'Gyro Sandwich',
    'Chicken Tenders + Fries',
    'Fried Chicken',
    'Breakfast for Dinner',
    'Meatloaf',
    'Pork Chops',
    'Lo Mein',
    'Mac & Cheese',
    'Eating Out/Pick Up',
    'Steak',
    'Tuna Salad',
    'Honey Garlic Chicken',
    'Chuck Roast',
    'Enchiladas',
    'Pizza',
    'Meatballs with Rice/Naan',
    'Hotdogs',
    'Ramen',
    'Omelette',
    `Shepherd's Pie`,
    'Find a new Recipe',
];